development:
  log_level: WARN
  telnet_server:
    host: 192.168.1.31
    port: 5678
  default_time_format: "%H%M%S"
  rest_server:
    port: 9999
  in12a_tubes:
    data_pin:  2
    clock_pin: 1
    latch_pin: 0
    count: 12
    write_blanks: true
  in1_pins:
    - 4
    - 5
    - 6
    - 7
    - 8
  in13_pins:
    - 0
    - 1
    - 2
    - 3



test:
  log_level: DEBUG
  telnet_server:
    host: localhost
    port: 5678
  rest_server:
    port: 9999
  tubes:
    data_pin:  3
    clock_pin: 2
    latch_pin: 1
    count: 12
  default_time_format: "%H%M%S"
  in12a_tubes:
    data_pin:  3
    clock_pin: 2
    latch_pin: 1
    count: 12
    write_blanks: true
  in1_pins:
    - 4
    - 5
    - 6
    - 7
    - 8
  in13_pins:
    - 0
    - 1
    - 2
    - 3

production:
