defaults: &defaults
  log_level: DEBUG
  database: nixon_pi.sqlite3
  telnet_server:
    host: 10.0.0.101
    port: 5678
  default_time_format: "%H%M%S"
  default_date_format: "%d  %m  %Y"
  in12a_tubes:
    data_pin:  2
    clock_pin: 1
    latch_pin: 0
    count: 12
    write_blanks: true
  in1_pins:
    - 8
    - 9
    - 10
    - 11
    - 12
  in13_pins:
    - 0
    - 1
    - 2
    - 3
  power_pin: 3
  rgb_pins:
    - 7
    - 5
    - 6
  background_led_pin: 4


development:
  <<: *defaults

test:
  <<: *defaults

production:
  database: nixon_pi.sqlite3
  log_level: INFO
  telnet_server:
      host: localhost
      port: 5678
  default_time_format: "%H%M%S"
  default_date_format: "%d  %m  %Y"
  in12a_tubes:
    data_pin:  2
    clock_pin: 1
    latch_pin: 0
    count: 12
    write_blanks: true
  in1_pins:
    - 8
    - 9
    - 10
    - 11
    - 12
  in13_pins:
    - 0
    - 1
    - 2
    - 3
  power_pin: 3
  rgb_pins:
    - 7
    - 5
    - 6
  background_led_pin: 4

